ProjectManagerBundle\Entity\Attachments:
    type: entity
    table: attachments
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        bindType:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
                default: ''
            column: bind_type
        bindId:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: bind_id
        file:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        info:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
