ProjectManagerBundle\Entity\Configuration:
    type: entity
    table: configuration
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        key:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        value:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
