ProjectManagerBundle\Entity\ExtraFields:
    type: entity
    table: extra_fields
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
        bindType:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
                default: ''
            column: bind_type
        type:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
        sortOrder:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: sort_order
        active:
            type: boolean
            nullable: true
        displayInList:
            type: boolean
            nullable: true
            column: display_in_list
    lifecycleCallbacks: {  }
