ProjectManagerBundle\Entity\Phases:
    type: entity
    table: phases
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
        defaultValues:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: default_values
    lifecycleCallbacks: {  }
