ProjectManagerBundle\Entity\TaskTypes:
    type: entity
    table: task_types
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
        sortOrder:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: sort_order
        defaultValue:
            type: boolean
            nullable: true
            column: default_value
        active:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
