ProjectManagerBundle\Entity\TaskGroups:
    type: entity
    table: task_groups
    indexes:
        fk_task_groups_projects:
            columns:
                - project_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
    manyToOne:
        project:
            targetEntity: Projects
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                project_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
