ProjectManagerBundle\Entity\TicketStatus:
    type: entity
    table: ticket_status
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
        group:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
        sortOrder:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: sort_order
        defaultValue:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: default_value
        active:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
    lifecycleCallbacks: {  }
