ProjectManagerBundle\Entity\TicketComments:
    type: entity
    table: ticket_comments
    indexes:
        fk_ticket_comments_tickets:
            columns:
                - ticket_id
        fk_ticket_comments_users:
            columns:
                - user_id
        k_ticket_comments_status:
            columns:
                - ticket_status_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
    manyToOne:
        ticket:
            targetEntity: Tickets
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ticket_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        ticketStatus:
            targetEntity: TicketStatus
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ticket_status_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
