ProjectManagerBundle\Entity\TicketTypes:
    type: entity
    table: ticket_types
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
        sortOrder:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: sort_order
        active:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
    lifecycleCallbacks: {  }
