ProjectManagerBundle\Entity\Users:
    type: entity
    table: users
    indexes:
        fk_pople_people_group:
            columns:
                - user_group_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
        photo:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
        culture:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
                default: ''
        active:
            type: boolean
            nullable: true
        skin:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
    manyToOne:
        userGroup:
            targetEntity: UserGroups
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_group_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
